# Generated by Django 5.2.3 on 2025-07-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Product Title')),
                ('link', models.CharField(max_length=128, verbose_name='Product Link')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('meta_score', models.FloatField(null=True, verbose_name='Metacritic Score')),
                ('meta_score_count', models.CharField(max_length=16, null=True, verbose_name='Meta Reviews Count')),
                ('user_score', models.FloatField(null=True, verbose_name='User Score')),
                ('user_score_count', models.CharField(max_length=16, null=True, verbose_name='User Reviews Count')),
                ('platforms', models.CharField(blank=True, max_length=128, null=True, verbose_name='Platforms')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('summary', models.TextField(blank=True, null=True)),
                ('developer', models.CharField(max_length=64, null=True, verbose_name='Developer')),
                ('publisher', models.CharField(max_length=64, null=True, verbose_name='Publisher')),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/games', verbose_name='Games Image')),
                ('bg_image', models.ImageField(null=True, upload_to='images/games/bg', verbose_name='Games BG Image')),
                ('yt_link', models.CharField(max_length=256, null=True, verbose_name='Youtube Trailer Link')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
            ],
        ),
    ]
