# Generated by Django 5.2.3 on 2025-07-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='yt_link',
        ),
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(max_length=128, verbose_name='Game Link'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.CharField(max_length=128, null=True, verbose_name='Platforms'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='Game Title'),
        ),
    ]
