# Generated by Django 5.2.3 on 2025-07-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_yt_link_alter_game_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='meta_score',
            field=models.CharField(max_length=4, null=True, verbose_name='Metacritic Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_score',
            field=models.CharField(max_length=4, null=True, verbose_name='User Score'),
        ),
    ]
