# Generated by Django 5.2.3 on 2025-07-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_meta_score_alter_game_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/games/bg', verbose_name='Games BG Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/games', verbose_name='Games Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(verbose_name='Game Link'),
        ),
        migrations.AlterField(
            model_name='game',
            name='meta_score',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Metacritic Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='meta_score_count',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Meta Reviews Count'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Platforms'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Game Title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_score',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='User Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_score_count',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='User Reviews Count'),
        ),
    ]
